### ISSUE TITLE
pulls panics on rare occasions

### ISSUE THREAD

**Issue by fkautz** [docker/gordon#162]
```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45a7b7]

goroutine 1 [running]:
github.com/docker/gordon.DisplayPullRequest(0xc208256000, 0xc208220f50, 0x7, 0xc208174ea0, 0x28, 0x1, 0xc208013b00, 0x1, 0x4)
	/home/fkautz/gopath/src/github.com/docker/gordon/display.go:137 +0x1fa7
main.mainCmd(0xc2080a40e0)
	/home/fkautz/gopath/src/github.com/docker/gordon/pulls/main.go:225 +0x2f0
github.com/codegangsta/cli.(*App).Run(0xc20807a000, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
	/home/fkautz/gopath/src/github.com/codegangsta/cli/app.go:182 +0xe5c
main.main()
	/home/fkautz/gopath/src/github.com/docker/gordon/pulls/main.go:555 +0xfe

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 13 [runnable]:
net/http.(*persistConn).readLoop(0xc2080a22c0)
	/usr/local/go/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:660 +0xc9f

goroutine 14 [select]:
net/http.(*persistConn).writeLoop(0xc2080a22c0)
	/usr/local/go/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:661 +0xcbc
```

**Comment by fkautz** [comment]
Should be fixed with #163
